### ISSUE TITLE
Point is moved

### ISSUE THREAD

**Issue by rubikitch** [xahlee/xah-replace-pairs#3]
I love your xah-replace-pairs.el!

xah-replace-pairs-region uses save-excursion,
but xah-replace-regexp-pairs-region and xah-replace-pairs-region-recursive do not.
So point is moved.

    ;;; Assumed that `keydef' package is installed.
    (require 'keydef)
    ;;; Prepare a test buffer.
    (keydef "C-c 1"
      (switch-to-buffer (get-buffer-create "*replace-test*"))
      (erase-buffer)
      (save-excursion
        (insert "one:1
    two:2
    three:3
    ")))

    ;;; C-c 1 C-c 2: point is moved
    (keydef "C-c 2"
      (xah-replace-pairs-region-recursive
       (point-min) (point-max)
      '((":" "::"))))
    ;;; C-c 1 C-c 3: point is not moved
    (keydef "C-c 3"
      (xah-replace-pairs-region
       (point-min) (point-max)
      '((":" "::"))))
    ;;; C-c 1 C-c 4: point is moved
    (keydef "C-c 4"
      (xah-replace-regexp-pairs-region
       (point-min) (point-max)
      '((":" "::"))))

**Comment by xahlee** [comment]
Thanks! fixed.
